[package]
name = "munchkin-sale-abi"
version = "0.0.0"
authors = [ "Munchkin token",]
edition = "2021"
publish = false

[dependencies.munchkin-sale]
path = ".."

[dependencies.elrond-wasm]
version = "0.18.2"

[dependencies.elrond-wasm-debug]
version = "0.18.2"
